version: '2'

services:
  miner1:
    image: ewasm/cpp-ethereum
    networks:
      ewasm:
        ipv4_address: 172.18.0.2
    environment:
      - NODE_ID=1

  miner2:
    image: ewasm/cpp-ethereum
    networks:
      ewasm:
        ipv4_address: 172.18.0.3
    environment:
      - NODE_ID=2

networks:
  ewasm:
    driver: bridge
    # enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24
        gateway: 172.18.0.1
# faucet:

# explorer
